-- Clean Supabase setup for the time reporting app.
-- Use this in a NEW Supabase project: SQL Editor -> New query -> Run.

-- Reset only the app tables. Do not run this in a Supabase project where you have other important data in these tables.
drop table if exists public.time_entries cascade;
drop table if exists public.users cascade;

create table public.users (
  id uuid primary key,
  username text unique not null,
  password_hash text not null,
  name text not null,
  role text not null check (role in ('employee', 'admin')),
  created_at timestamptz not null default now()
);

create table public.time_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  date date not null,
  company_id text not null,
  project_id text not null,
  hours numeric not null check (hours > 0 and hours <= 24),
  note text default '',
  created_at timestamptz not null default now()
);

insert into public.users (id, username, password_hash, name, role) values
  ('00000000-0000-0000-0000-000000000001', 'admin', 'admin123', 'Admin User', 'admin'),
  ('00000000-0000-0000-0000-000000000002', 'anna',  'anna123',  'Anna Employee', 'employee'),
  ('00000000-0000-0000-0000-000000000003', 'erik',  'erik123',  'Erik Employee', 'employee');

insert into public.time_entries (user_id, date, company_id, project_id, hours, note)
values ('00000000-0000-0000-0000-000000000002', current_date, 'nordic_trials', 'nt_ops', 1.5, 'Sample entry');

alter table public.users enable row level security;
alter table public.time_entries enable row level security;

create policy "app_read_users"
on public.users
for select
to anon
using (true);

create policy "app_read_time_entries"
on public.time_entries
for select
to anon
using (true);

create policy "app_insert_time_entries"
on public.time_entries
for insert
to anon
with check (true);

create policy "app_delete_time_entries"
on public.time_entries
for delete
to anon
using (true);
